name: 'Terraform Destroy'

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "YordanOrg"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "website_check_serverless"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: destroy-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: destroy-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.destroy-upload.outputs.configuration_version_id }}
          is_destroy: true

      - name: Apply Destroy
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.destroy-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: destroy-apply
        with:
          run: ${{ steps.destroy-run.outputs.run_id }}
          comment: "Manual Destroy Run from GitHub Actions"